
// Generated by build tool, do not edit
using System;
using System.Reflection;
[assembly: AssemblyCopyright("Copyright © 2021 Topten Software. All Rights Reserved")]
[assembly: AssemblyVersion("0.1.105")]
[assembly: AssemblyFileVersion("0.1.105")]
[assembly: AssemblyCompany("Topten Software")]
[assembly: AssemblyProduct("nuspec_tool")]

static class BuildInfo
{
	public static DateTime Date = new DateTime(2021, 11, 9, 0, 18, 11, DateTimeKind.Utc);
}
	